export const NAVIGATION_NAME = {
  DIARY_STACK_NAVIGATION: "DIARY_STACK_NAVIGATION",

  ADD_DIARY: "ADD DIARY",
  DIARY_DETAIL: "DIARY DETAIL",
  DIARY_LIST: "DIARY LIST",
  SETTING: "SETTING",
  ADD_PASSWORD: "ADD PASSWORD",
}
